import { Router } from 'express';
import {
  createEvent,
  getAllEvents,
  getAllEventsWithInactive,
  getEventById,
  disableEventById,
  reactivateEventById,
  deleteEventById,
  updateEvent,
  getUsersByEventId,
  removeUserFromEvent,
  addUserToEvent
} from '../controller/eventController';

const router = Router();

/**
 * @swagger
 * components:
 *   schemas:
 *     Event:
 *       type: object
 *       required:
 *         - name
 *         - schedule
 *       properties:
 *         id:
 *           type: string
 *           description: ID generated by MongoDB
 *         name:
 *           type: string
 *         schedule:
 *           type: string
 *         address:
 *           type: string
 *         active:
 *           type: boolean
 *           description: Indicates if the event is active
 *       example:
 *         name: "Technology Conference"
 *         schedule: "2024-01-15T10:00:00Z"
 *         address: "Main Auditorium"
 *         active: true
 */

// =============================================
// GET METHODS - EVENTS
// =============================================

/**
 * @swagger
 * /api/event:
 *   get:
 *     summary: Get all active events (paginated)
 *     tags: [Events]
 *     parameters:
 *       - in: query
 *         name: skip
 *         schema:
 *           type: integer
 *         description: Number of records to skip (pagination)
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *         description: Number of records to return (pagination)
 *     responses:
 *       200:
 *         description: List of active events obtained successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 events:
 *                   type: array
 *                   items:
 *                     $ref: '#/components/schemas/Event'
 *                 pagination:
 *                   type: object
 *                   properties:
 *                     skip:
 *                       type: integer
 *                     limit:
 *                       type: integer
 *                     total:
 *                       type: integer
 *                     hasMore:
 *                       type: boolean
 */
router.get('/', getAllEvents);

/**
 * @swagger
 * /api/event/all/inactive-included:
 *   get:
 *     summary: Get all events including inactive ones (paginated) - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: query
 *         name: skip
 *         schema:
 *           type: integer
 *         description: Number of records to skip (pagination)
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *         description: Number of records to return (pagination)
 *     responses:
 *       200:
 *         description: List of all events obtained successfully
 *       401:
 *         description: Admin authentication required
 *       403:
 *         description: You do not have admin permissions
 */
router.get('/all/inactive-included', getAllEventsWithInactive);

/**
 * @swagger
 * /api/event/{id}:
 *   get:
 *     summary: Get an active event by ID
 *     tags: [Events]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Event ID
 *     responses:
 *       200:
 *         description: Event found
 *       404:
 *         description: Event not found
 */
router.get('/:id', getEventById);

// =============================================
// POST METHODS - EVENTS
// =============================================

/**
 * @swagger
 * /api/event:
 *   post:
 *     summary: Create a new event
 *     tags: [Events]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Event'
 *     responses:
 *       201:
 *         description: Event created successfully
 *       400:
 *         description: Error in event data
 */
router.post('/', createEvent);

// =============================================
// PUT METHODS - EVENTS
// =============================================

/**
 * @swagger
 * /api/event/{id}:
 *   put:
 *     summary: Disable an event by ID (Soft Delete)
 *     tags: [Events]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Event ID
 *     responses:
 *       200:
 *         description: Event disabled successfully
 *       404:
 *         description: Event not found
 */
router.put('/:id', disableEventById);

/**
 * @swagger
 * /api/event/{id}/reactivate:
 *   put:
 *     summary: Reactivate an event by ID
 *     tags: [Events]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Event ID
 *     responses:
 *       200:
 *         description: Event reactivated successfully
 *       404:
 *         description: Event not found
 */
router.put('/:id/reactivate', reactivateEventById);

// =============================================
// DELETE METHODS - EVENTS (ADMIN)
// =============================================

/**
 * @swagger
 * /api/event/hard/{id}:
 *   delete:
 *     summary: Permanently delete an event by ID (Hard Delete) - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Event ID
 *     responses:
 *       200:
 *         description: Event permanently deleted
 *       404:
 *         description: Event not found
 */
router.delete('/hard/:id', deleteEventById);

/**
 * @swagger
 * /api/event/{id}:
 *   patch:
 *     summary: Update event details by ID
 *     tags: [Events]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Event ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Event'
 *     responses:
 *       200:
 *         description: Event updated successfully
 *       404:
 *         description: Event not found
 */
router.patch('/:id', updateEvent);

/**
 * @swagger
 * /api/event/{id}/users:
 *   get:
 *     summary: Get all users participating in an event
 *     tags: [Events]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Event ID
 *     responses:
 *       200:
 *         description: List of users in the event
 *       404:
 *         description: Event not found
 */
router.get('/:id/users', getUsersByEventId);

/**
 * @swagger
 * /api/event/{eventId}/user/{userId}:
 *   put:
 *     summary: Add a user to an event
 *     tags: [Events]
 *     parameters:
 *       - in: path
 *         name: eventId
 *         required: true
 *         schema:
 *           type: string
 *         description: Event ID
 *       - in: path
 *         name: userId
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     responses:
 *       200:
 *         description: User added to event
 *       404:
 *         description: Event or user not found
 */
router.put('/:eventId/user/:userId', addUserToEvent);

/**
 * @swagger
 * /api/event/{eventId}/user/{userId}:
 *   delete:
 *     summary: Remove a user from an event
 *     tags: [Events]
 *     parameters:
 *       - in: path
 *         name: eventId
 *         required: true
 *         schema:
 *           type: string
 *         description: Event ID
 *       - in: path
 *         name: userId
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     responses:
 *       200:
 *         description: User removed from event
 *       404:
 *         description: Event or user not found
 */
router.delete('/:eventId/user/:userId', removeUserFromEvent);

export default router;