import { Router } from 'express';
import {
  createUser,
  createAdminUser,
  createFirstAdmin,
  getAllUsers,
  getAllUsersWithInactive,
  getUserById,
  getUserByUsername,
  updateUserById,
  updateUserByUsername,
  disableUserById,
  disableUserByUsername,
  reactivateUserById,
  reactivateUserByUsername,
  makeUserAdmin,
  removeUserAdmin,
  deleteUserById,
  deleteUserByUsername,
  addEventToUser,
  loginUser,           
  loginBackoffice
} from '../controller/userController';

const router = Router();

/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - username
 *         - email
 *         - password
 *       properties:
 *         id:
 *           type: string
 *           description: ID generated by MongoDB
 *         username:
 *           type: string
 *         email:
 *           type: string
 *         password:
 *           type: string
 *         birthday:
 *           type: string
 *           format: date
 *         active:
 *           type: boolean
 *           description: Indicates if the user is active
 *         admin:
 *           type: boolean
 *           description: Indicates if the user is an administrator
 *       example:
 *         username: "userExample"
 *         email: "user@example.com"
 *         password: "123456"
 *         birthday: "2000-01-01"
 *         active: true
 *         admin: false
 */

// =============================================
// GET METHODS - USERS
// =============================================

/**
 * @swagger
 * /api/user:
 *   get:
 *     summary: Get all active users (paginated)
 *     tags: [Users]
 *     parameters:
 *       - in: query
 *         name: skip
 *         schema:
 *           type: integer
 *         description: Number of records to skip (pagination)
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *         description: Number of records to return (pagination)
 *     responses:
 *       200:
 *         description: List of active users obtained successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 users:
 *                   type: array
 *                   items:
 *                     $ref: '#/components/schemas/User'
 *                 pagination:
 *                   type: object
 *                   properties:
 *                     skip:
 *                       type: integer
 *                     limit:
 *                       type: integer
 *                     total:
 *                       type: integer
 *                     hasMore:
 *                       type: boolean
 */
router.get('/', getAllUsers);

/**
 * @swagger
 * /api/user/all/inactive-included:
 *   get:
 *     summary: Get all users including inactive ones (paginated) - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: query
 *         name: skip
 *         schema:
 *           type: integer
 *         description: Number of records to skip (pagination)
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *         description: Number of records to return (pagination)
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: List of all users obtained successfully
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 */
router.get('/all/inactive-included', getAllUsersWithInactive);

/**
 * @swagger
 * /api/user/{id}:
 *   get:
 *     summary: Get an active user by ID
 *     tags: [Users]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     responses:
 *       200:
 *         description: User found
 *       404:
 *         description: User not found
 */
router.get('/:id', getUserById);

/**
 * @swagger
 * /api/user/username/{username}:
 *   get:
 *     summary: Get an active user by username
 *     tags: [Users]
 *     parameters:
 *       - in: path
 *         name: username
 *         required: true
 *         schema:
 *           type: string
 *         description: Username
 *     responses:
 *       200:
 *         description: User found
 *       404:
 *         description: User not found
 */
router.get('/username/:username', getUserByUsername);

// =============================================
// POST METHODS - USERS & AUTHENTICATION
// =============================================

/**
 * @swagger
 * /api/user:
 *   post:
 *     summary: Create a new user
 *     tags: [Users]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *     responses:
 *       201:
 *         description: User created successfully
 *       400:
 *         description: Error in user data
 */
router.post('/', createUser);

/**
 * @swagger
 * /api/user/auth/login:
 *   post:
 *     summary: User login (only active users)
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - username
 *               - password
 *             properties:
 *               username:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       200:
 *         description: Login successful
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                 user:
 *                   $ref: '#/components/schemas/User'
 *       401:
 *         description: Incorrect credentials or user disabled
 */
router.post('/auth/login', loginUser);

/**
 * @swagger
 * /api/user/auth/login-backoffice:
 *   post:
 *     summary: Backoffice login (administrators only)
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - username
 *               - password
 *             properties:
 *               username:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       200:
 *         description: Backoffice login successful
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                 user:
 *                   $ref: '#/components/schemas/User'
 *                 isAdmin:
 *                   type: boolean
 *       401:
 *         description: Incorrect credentials or you do not have admin permissions
 */
router.post('/auth/login-backoffice', loginBackoffice);

/**
 * @swagger
 * /api/user/auth/first-admin:
 *   post:
 *     summary: Create first administrator user (only if no admins in the system)
 *     tags: [Administration]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - username
 *               - email
 *               - password
 *               - birthday
 *             properties:
 *               username:
 *                 type: string
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *               birthday:
 *                 type: string
 *                 format: date
 *     responses:
 *       201:
 *         description: First administrator user created successfully
 *       400:
 *         description: Admins already exist in the system
 *       500:
 *         description: Failed to create first administrator
 */
router.post('/auth/first-admin', createFirstAdmin);

/**
 * @swagger
 * /api/user/admin/create:
 *   post:
 *     summary: Create new administrator user - Admin only
 *     tags: [Administration]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *               - username
 *               - email
 *               - password
 *               - birthday
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *               username:
 *                 type: string
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *               birthday:
 *                 type: string
 *                 format: date
 *     responses:
 *       201:
 *         description: Administrator user created successfully
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 *       500:
 *         description: Failed to create administrator user
 */
router.post('/admin/create', createAdminUser);

// =============================================
// PUT METHODS - USERS
// =============================================

/**
 * @swagger
 * /api/user/{id}:
 *   put:
 *     summary: Update an active user by ID
 *     tags: [Users]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *     responses:
 *       200:
 *         description: User updated successfully
 *       404:
 *         description: User not found
 */
router.put('/:id', updateUserById);

/**
 * @swagger
 * /api/user/username/{username}:
 *   put:
 *     summary: Update an active user by username
 *     tags: [Users]
 *     parameters:
 *       - in: path
 *         name: username
 *         required: true
 *         schema:
 *           type: string
 *         description: Username
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *     responses:
 *       200:
 *         description: User updated successfully
 *       404:
 *         description: User not found
 */
router.put('/username/:username', updateUserByUsername);

/**
 * @swagger
 * /api/user/{id}/disable:
 *   put:
 *     summary: Disable a user by ID (Soft Delete) - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: User disabled successfully
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 *       404:
 *         description: User not found
 */
router.put('/:id/disable', disableUserById);

/**
 * @swagger
 * /api/user/username/{username}/disable:
 *   put:
 *     summary: Disable a user by username (Soft Delete) - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: path
 *         name: username
 *         required: true
 *         schema:
 *           type: string
 *         description: Username
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: User disabled successfully
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 *       404:
 *         description: User not found
 */
router.put('/username/:username/disable', disableUserByUsername);

/**
 * @swagger
 * /api/user/{id}/reactivate:
 *   put:
 *     summary: Reactivate a user by ID - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: User reactivated successfully
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 *       404:
 *         description: User not found
 */
router.put('/:id/reactivate', reactivateUserById);

/**
 * @swagger
 * /api/user/username/{username}/reactivate:
 *   put:
 *     summary: Reactivate a user by username - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: path
 *         name: username
 *         required: true
 *         schema:
 *           type: string
 *         description: Username
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: User reactivated successfully
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 *       404:
 *         description: User not found
 */
router.put('/username/:username/reactivate', reactivateUserByUsername);

/**
 * @swagger
 * /api/user/{id}/make-admin:
 *   put:
 *     summary: Convert user to administrator - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: User converted to administrator successfully
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 *       404:
 *         description: User not found
 */
router.put('/:id/make-admin', makeUserAdmin);

/**
 * @swagger
 * /api/user/{id}/remove-admin:
 *   put:
 *     summary: Remove administrator permissions - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: Administrator permissions removed successfully
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 *       404:
 *         description: User not found
 */
router.put('/:id/remove-admin', removeUserAdmin);

/**
 * @swagger
 * /api/user/{id}/addEvent:
 *   put:
 *     summary: Add event to a user
 *     tags: [Users]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - eventId
 *             properties:
 *               eventId:
 *                 type: string
 *     responses:
 *       200:
 *         description: Event added to user successfully
 *       400:
 *         description: Missing eventId
 *       404:
 *         description: User not found
 */
router.put('/:id/addEvent', addEventToUser);

// =============================================
// DELETE METHODS - ADMINISTRATION
// =============================================

/**
 * @swagger
 * /api/user/hard/{id}:
 *   delete:
 *     summary: Permanently delete a user by ID (Hard Delete) - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: User ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: User permanently deleted
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 *       404:
 *         description: User not found
 */
router.delete('/hard/:id', deleteUserById);

/**
 * @swagger
 * /api/user/hard/username/{username}:
 *   delete:
 *     summary: Permanently delete a user by username (Hard Delete) - Admin only
 *     tags: [Administration]
 *     parameters:
 *       - in: path
 *         name: username
 *         required: true
 *         schema:
 *           type: string
 *         description: Username
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - adminUsername
 *               - adminPassword
 *             properties:
 *               adminUsername:
 *                 type: string
 *               adminPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: User permanently deleted
 *       401:
 *         description: Admin credentials required
 *       403:
 *         description: You do not have admin permissions
 *       404:
 *         description: User not found
 */
router.delete('/hard/username/:username', deleteUserByUsername);

export default router;